services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - 3001:3001
  database:
    build: ./database/database
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ireallydontcare
