services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  api-server:
    build: ./api-server
    ports:
      - 3001:3001
  database:
    image: postgres:16.1
    ports:
      - 8001:5432
    environment:
      POSTGRES_PASSWORD: ireallydontcare
